### ISSUE TITLE
FLOATING CRATE.

### ISSUE THREAD

**Issue by BytewaveMLP** [HorseyHangout/au_skeld#36]
FLOATING CRATE.
FLOATING CRATE.
FLOATING CRATE.
FLOATING CRATE.
FLOATING CRATE.
FLOATING CRATE.
FLOATING CRATE.

that is all.

**Comment by NotMyWing** [comment]
FLOATING CRATE.

**Comment by BytewaveMLP** [comment]
(related to #15)
